### ISSUE TITLE
Arrays of structs

### ISSUE THREAD

**Issue by josephguillaume** [duncantl/XMLRPC#1]
It seems like current code does not support arrays of structs. (I also found this Stackoverflow post https://stackoverflow.com/questions/35462179/passing-array-to-xml-rpc-using-r)
I got a working solution for my problem with the code below. I'm not sure whether it is a general solution.

```
setMethod("rpc.serialize", "list",
          function(x, ...) {   
            if(length(names(x))) {
              a = newXMLNode("struct")
              sapply(names(x), function(id) {
                type = basicTypeMap[typeof(x[[id]])]
                newXMLNode("member", newXMLNode("name", id),
                           rpc.serialize(x[[id]]
                           ),
                           parent = a)
              })
              a
            } else {
              a = newXMLNode("array")
              data = newXMLNode("data", parent = a)
              sapply(x, function(x) {
                newXMLNode("value", rpc.serialize(x),parent = data)
              })
              a
            }
          })
```

This overrides: https://github.com/duncantl/XMLRPC/blob/master/R/serialize.R#L183

**Comment by duncantl** [comment]
Thanks Joseph. 
Am I correct in my reading that the sole change is in the else clause and specifially
the second argument to newXMLNode("value", ...) being rpc.serialize() rather than
newXMLNode().  That makes perfect sense. Just want to check if there are other changes. 
Thanks
D.

**Comment by josephguillaume** [comment]
Thanks for the reply!
Yes, the change only affects the else clause (i.e. lists without names are interpreted as arrays).
I had just replaced the whole sapply call, because basicTypeMap has no entry for list and I suspected that type based logic wasn't needed at all (I haven't tested that)

**Comment by duncantl** [comment]
Thanks Joseph. I committed the change and also added tests/serialize.R file to test this.
If you have the time, can you verify the changes I made are correct. (Since this wasn't a diff/pull request, I made it manually.)

Thanks again.

**Comment by josephguillaume** [comment]
Looks good and works for me. Thanks!
Note that elName is not used. https://github.com/duncantl/XMLRPC/blob/master/R/serialize.R#L201

**Comment by duncantl** [comment]
Thanks. Removed now and version number bumped up.
I'll leave it to you to close this if/when you think it is appropriate.
Thanks again.

**Comment by josephguillaume** [comment]
Perfect.
